// client/src/app/pages/userlogin/userlogin.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-userlogin',
  imports: [],
  templateUrl: './userlogin.component.html',
})
export class UserloginComponent {}

<div class="w-screen h-dvh flex">
  <!-- Left Image -->
  <div class="w-1/2 h-dvh border-r border-neutral-600/30">
    <img
      src="/images/new (4).png"
      alt="login-image"
      class="w-full h-full object-cover"
    />
  </div>

  <form
    [formGroup]="userFrom"
    (ngSubmit)="onSubmit()"
    class="w-1/2 bg-white h-dvh"
  >
    <div class="w-full h-full flex flex-col justify-center gap-4 px-24">
      <div class="flex flex-col items-center gap-3 mb-2">
        <span class="text-4xl font-semibold">IDCC</span>
        <span class="text-center text-xs">
          Team up, code fast, and conquer challenges—fun and skills combined!
        </span>
      </div>

      <div formGroupName="participant1" class="flex flex-col text-xs gap-1">
        <span class="text-sm text-black">Participant 1</span>
        <div class="flex gap-2 text-sm text-gray-600">
          <div class="flex flex-col flex-1 gap-1">
            <label>Name</label>
            <input
              type="text"
              formControlName="name"
              class="px-4 py-2 text-base text-black border border-neutral-800 rounded"
            />
            <span
              class="text-red-600 text-xs"
              *ngIf="
                userFrom.get('participant1.name')?.touched &&
                userFrom.get('participant1.name')?.hasError('required')
              "
            >
              Name is required
            </span>
          </div>
          <div class="flex flex-col flex-1 gap-1">
            <label>Reg.no</label>
            <input
              type="text"
              formControlName="regno"
              class="px-4 py-2 text-base text-black border border-neutral-800 rounded"
            />
            <span
              class="text-red-600 text-xs"
              *ngIf="
                userFrom.get('participant1.regno')?.touched &&
                userFrom.get('participant1.regno')?.hasError('required')
              "
            >
              Reg no is required
            </span>
          </div>
        </div>
      </div>

      <div formGroupName="participant2" class="flex flex-col text-xs gap-1">
        <span class="text-sm text-black">Participant 2</span>
        <div class="flex gap-2 text-sm text-gray-600">
          <div class="flex flex-col flex-1 gap-1">
            <label>Name</label>
            <input
              type="text"
              formControlName="name"
              class="px-4 py-2 text-base text-black border border-neutral-800 rounded"
            />
            <span
              class="text-red-600 text-xs"
              *ngIf="
                userFrom.get('participant2.name')?.touched &&
                userFrom.get('participant2.name')?.hasError('required')
              "
            >
              Name is required
            </span>
          </div>
          <div class="flex flex-col flex-1 gap-1">
            <label>Reg.no</label>
            <input
              type="text"
              formControlName="regno"
              class="px-4 py-2 text-base border border-neutral-800 rounded"
            />
            <span
              class="text-red-600 text-xs"
              *ngIf="
                userFrom.get('participant2.regno')?.touched &&
                userFrom.get('participant2.regno')?.hasError('required')
              "
            >
              Reg no is required
            </span>
          </div>
        </div>
      </div>

      <div class="flex flex-col text-sm gap-1">
        <label>Email</label>
        <input
          type="email"
          formControlName="email"
          class="px-4 py-2 text-base border border-neutral-800 rounded"
        />
        <span
          class="text-red-600 text-xs"
          *ngIf="
            userFrom.get('email')?.touched &&
            userFrom.get('email')?.hasError('required')
          "
        >
          Email is required
        </span>
        <span
          class="text-red-600 text-xs"
          *ngIf="
            userFrom.get('email')?.touched &&
            userFrom.get('email')?.hasError('email')
          "
        >
          Enter a valid email
        </span>
      </div>

      <div class="flex flex-col text-sm gap-1">
        <label>Phone</label>
        <input
          type="tel"
          formControlName="phone"
          class="px-4 py-2 text-base border border-neutral-800 rounded"
        />
        <span
          class="text-red-600 text-xs"
          *ngIf="
            userFrom.get('phone')?.touched &&
            userFrom.get('phone')?.hasError('required')
          "
        >
          Phone number is required
        </span>
        <span
          class="text-red-600 text-xs"
          *ngIf="
            userFrom.get('phone')?.touched &&
            userFrom.get('phone')?.hasError('pattern')
          "
        >
          Phone must be 10 digits
        </span>
      </div>

      <button
        type="submit"
        [disabled]="userFrom.invalid"
        class="bg-black px-4 py-3 text-base text-white rounded mt-2 disabled:opacity-90"
      >
        <span>Continue</span>
      </button>
    </div>
  </form>
</div>

// client/src/pages/UserLogin.jsx
import React from "react";
import UserLoginImage from "../assets/images/userloginimage.png";
const UserLogin = () => {
	return (
		<div className="w-screen h-dvh flex">
			<div className="w-1/2 h-dvh border-r border-neutral-600/30">
				<img
					src={UserLoginImage}
					alt="login-image"
					className="w-full h-full object-cover"
				/>
			</div>

			<form className="w-1/2 bg-white h-dvh">
				<div className="w-full h-full flex flex-col justify-center gap-4 px-24">
					<div className="flex flex-col items-center gap-3 mb-3">
						<div className="flex flex-col items-center gap-2">
							<span className="text-4xl font-semibold  leading-none">
								Logiq
							</span>
							<span className="text-xs font-bold">BY IDCC</span>
						</div>
						<span className="text-center text-base my-2">
							where algorithms meet adrenaline.
						</span>
					</div>

					<div className="flex flex-col text-xs gap-1">
						<span className="text-sm text-black font-medium">
							Participant 1
						</span>
						<div className="flex gap-2 text-sm ">
							<div className="flex flex-col flex-1 gap-1">
								<label>Name</label>
								<input
									type="text"
									className="px-4 py-2 text-base text-black border border-neutral-800/40 rounded"
								/>
							</div>
							<div className="flex flex-col flex-1 gap-1">
								<label>Reg.no</label>
								<input
									type="text"
									className="px-4 py-2 text-base text-black border border-neutral-800/40 rounded"
								/>
							</div>
						</div>
					</div>

					<div className="flex flex-col text-xs gap-1">
						<span className="text-sm text-black font-medium">
							Participant 2
						</span>
						<div className="flex gap-2 text-sm">
							<div className="flex flex-col flex-1 gap-1">
								<label>Name</label>
								<input
									type="text"
									className="px-4 py-2 text-base text-black border border-neutral-800/40 rounded"
								/>
							</div>
							<div className="flex flex-col flex-1 gap-1">
								<label>Reg.no</label>
								<input
									type="text"
									className="px-4 py-2 text-base border border-neutral-800/40 rounded"
								/>
							</div>
						</div>
					</div>

					<div className="flex flex-col text-sm gap-1">
						<label>Email</label>
						<input
							type="email"
							className="px-4 py-2 text-base border border-neutral-800/40 rounded"
						/>
					</div>

					<div className="flex flex-col text-sm gap-1">
						<label>Phone</label>
						<input
							type="tel"
							className="px-4 py-2 text-base border border-neutral-800/40 rounded"
						/>
					</div>

					<button
						type="submit"
						className="bg-black px-4 py-3 text-base text-white rounded mt-2 disabled:opacity-90"
					>
						<span>Continue</span>
					</button>
				</div>
			</form>
		</div>
	);
};

export default UserLogin;
