// client/src/app/layouts/adminlayout/adminlayout.component.ts
import { Component } from '@angular/core';
import { AdminnavbarComponent } from '../../components/adminnavbar/adminnavbar.component';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-adminlayout',
  imports: [AdminnavbarComponent, RouterOutlet],
  templateUrl: './adminlayout.component.html',
})
export class AdminlayoutComponent {}

<ng-container *ngIf="adminAuthService.isCheckingAuth(); else adminLayout">
  <!-- Loading screen while guard is checking -->
  <div class="flex items-center justify-center h-screen">
    <p class="text-lg">Checking admin access...</p>
  </div>
</ng-container>

<ng-template #adminLayout>
  <main class="w-screen h-dvh overflow-hidden  flex flex-col">
    <nav class="w-full h-16 border-b border-neutral-800/30">
      <app-adminnavbar></app-adminnavbar>
    </nav>
    <section class="flex-1 overflow-y-auto flex">
      <div class="w-[12vw] h-full">
        <app-admin-side-menu></app-admin-side-menu>
      </div>
      <div class="flex-1 h-full">
        nothing...
        <router-outlet></router-outlet>
      </div>
    </section>
  </main>
</ng-template>

// client/src/layouts/AdminLayout.jsx
import React from "react";
import Navbar from "../components/Admin/Navbar";
import SideMenu from "../components/Admin/SideMenu";
import { Outlet } from "react-router";
const AdminLayout = () => {
    return (
        <main className="w-screen h-dvh flex flex-col">
            <nav className="h-16">
                <Navbar />
            </nav>
            <section className="flex w-full h-[calc(100%-4rem)] ">
                <div className="w-44 ">
                    <SideMenu />
                </div>
                <div className="h-full w-[calc(100%-11rem)]">
                    <Outlet />
                </div>
            </section>
        </main>
    );
};

export default AdminLayout;
